
spring:
  redis:
    lettuce:
      pool:
        max-active: 500
        max-wait: 10000
        min-idle: 10
        max-idle: 100
      shutdown-timeout: 5000
    database: 0
    host: redis.eastcom.io
    port: 6379
    password: AS@redis